language: node_js
node_js:
  - "6.1"
script:
- date
- mkdir dist
- cp security.txt humans.txt robots.txt ./dist
- cat index.html | sed 's|UA-XXXXX-Y|'$GA_KEY_ID'|g' > ./dist/index.html
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  region: $AWS_REGION
  skip_cleanup: true
  acl: public_read
  # Set the Cache-Control header.
  cache_control: "max-age=21600"
  local_dir: dist
  on:
    branch: master
after_deploy:
  - rm -rf ./dist
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
